sudo: required
language: cpp
services:
  - docker
before_install:
  - docker pull engelphi/docker-cpp-image:latest
  - docker run -itd --name build engelphi/docker-cpp-image
  - docker exec build git clone https://github.com/engelphi/algorithm.git
script:
  - docker exec build sh -c 'cd algorithm && mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=clang++'
  - docker exec build sh -c 'cd algorithm/build && make algorithm_coverage'
