sudo: required
language: cpp
env:
  - ci_env=`(curl -s https://codecov.io/env) | bash`
services:
  - docker
before_install:
  - docker pull engelphi/docker-cpp-image:latest
  - docker run $ci_env -itd --name build engelphi/docker-cpp-image
  - docker exec build git clone https://github.com/engelphi/algorithm.git
script:
  - docker exec build sh -c 'cd algorithm && mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=clang++'
  - docker exec build sh -c 'cd algorithm/build && make'
after_success:
  - docker exec build sh -c 'cd algorithm/build && make algorithm_coverage'
  - docker exec build sh -c 'cd algorithm/build && $(curl -s https://codecov.io/bash > codecov.sh) && chmod +x codecov.sh && ./codecov.sh -X gcov -s coverage -f lcov.info || echo "Codecov did not collect coverage reports"'
